### ISSUE TITLE
SFMLOrthogonalLayer ignores tile spacing

### ISSUE THREAD

**Issue by oarmstrong** [fallahn/tmxlite#1]
I have a tileset which has a 1px spacing set on it. Unfortunately your provided `SFMLOrthogonalLayer.hpp` file doesn't seem to take into account the spacing of the tiles.

I've looked through the source but can't really work out where the modifications would be required.  Would you mind pointing me in the right direction?

**Comment by fallahn** [comment]
Sure, the sample code doesn't take into account quite a few features, including tile spacing (it's just a sample ;) ). If you want to run with the sample code, however, you'd probably want to look into [this](https://github.com/fallahn/tmxlite/blob/master/tmxlite/include/render/SFMLOrthogonalLayer.hpp#L129) loop, and read out the tile set properties when creating the vertex arrays, setting the adjusted tile set coordinates. If you'd prefer a different tack I have [an implementation](https://github.com/fallahn/xygine/blob/master/xygine/src/components/ComponentTileMapLayer.cpp) which draws the tiles with a [shader](https://github.com/fallahn/xygine/blob/master/xygine/include/xygine/shaders/Tilemap.hpp), which accounts for tile space, tile flipping etc, and helps prevent artifacting caused by vertex arrays.

**Comment by oarmstrong** [comment]
I had just worked it out by the time you posted that :)

I'll tidy up and hit you with a pull request if you'd like to merge it in.
