### ISSUE TITLE
Minimal working example for SFML?

### ISSUE THREAD

**Issue by rohanharikr** [fallahn/tmxlite#101]
Hey, I see that there is an example code for SFML and I understand the intent behind making it be 600 lines showing off some functionalities but was wondering if there was a minimal working example of tmxlite for SFML. By minimal example, I mean just drawing one tile to the screen.

**Comment by ldornbusch** [comment]
The problem is less the SFML code but the complex tmx-format.  .tmx has a lot of options (multilayers, different layertypes, tilesets, animation, etc.). All these capabilities need to be accounted for(and tmxlite does it!). However a minimal example with a single tile does not show much information _how_ to use the api for the different capabilities to work with them. 
The draw() method shows how to do the _real_ drawing, but it is merely a call to draw the vertex array.
