### ISSUE TITLE
Error parsing collection of images tilesets

### ISSUE THREAD

**Issue by Clever-Boy** [fallahn/tmxlite#26]
Hi,

I am probably not doing it right and is also probably not a bug, but the SFML Sample map example errors if if the Map is created using "Collection of Images". I am not sure why that should be an error. Is anyone else facing a similar error. My tiles are 505x505

Failed to load image "". Reason: Unable to open file 

Ex: Dessert.Tmx
 tileset firstgid="1" source="images/tilemap/Dessert1.tsx"
  
Dessert1.tsx 
  image width="505" height="505" source="platform-block-01.png"

**Comment by fallahn** [comment]
To see if this is a bug use your debugger to inspect the tmx::Tileset object and check it has parsed the file properly - ie all the fields contain the correct information such as image file name and tile size. If this isn't loaded properly then it could well be a bug in tmxlite which I'll look into. On the other hand it could be, as [this comment](https://github.com/fallahn/tmxlite/blob/master/SFMLExample/src/SFMLOrthogonalLayer.hpp#L28) suggests, that the SFML example doesn't implement rendering with collection of images tile sets.

**Comment by DennisSc** [comment]
I get a "division by zero" exception when trying to load a map containing "collection of image" layers, at a point where it calculates something from texture size
```
auto texSize = m_chunkArrays.back()->getTextureSize();
tsTileCount.x = texSize.x / tileSize.x; 
```

which is nice - since it then stops at the exact right place to debug. :)

According to my debugger, parsing the "collection of images" layer results in an empty "m_imagePath" in m_tilesets[0], but instead a child element "m_tilesets[0].m_tiles[0]" at this point contains the correct value in "imagepath".

As a workaround, maybe you could export your "collection of images" to an actual image using Tiled, and then use that image as tileset in a regular, tileset-based layer?
