### ISSUE TITLE
Are tile animations supported?

### ISSUE THREAD

**Issue by Luke004** [fallahn/tmxlite#37]
Right now I have a _MapLayer_ containing my map data which gets rendered like this:
`window.draw(*mapLayer);`
by the _RenderWindow_.
I have now included a small animation in this layer but it is only shown in _Tiled_, not in the final C++ program.
Is there a special method I need to call in order to render animations?
I have seen this code snippet in the _Tileset.hpp_ file:

```
Tile::Animation::Frame frame;
frame.duration = frameNode.attribute("duration").as_int();
frame.tileID = frameNode.attribute("tileid").as_int();
tile.animation.frames.push_back(frame);
```
Do I need to execute this specificly? And if so, how?

**Comment by fallahn** [comment]
The map loader will load the animation data, but the SFML example doesn't do anything to render it, you'll need to do that yourself. The included examples are a quick start to rendering tmx data, rather than a comprehensive set of rendering tools. The idea behind tmxlite is that you can use any rendering library you like (SFML, SDL, DirectX etc) so that it best fits your project's needs. There are some [animation examples](https://github.com/SFML/SFML/wiki/Source:-AnimatedSprite) on the SFML wiki which might help.

**Comment by Luke004** [comment]
Many thanks!
