### ISSUE TITLE
Replacing a single tile during run

### ISSUE THREAD

**Issue by Luke004** [fallahn/tmxlite#38]
https://github.com/fallahn/tmxlite/blob/1e756d983de5c89605927b46822c304d72194bdc/SFMLExample/src/SFMLOrthogonalLayer.hpp#L124

I am trying to modify the _SFMLOrthogonalLayer.hpp_  so that I can update a single tile when the player destroys it (replace it with another tileID), but I'm having problems accessing the ChunkArray inside the Chunk which Vertices I would have to modify in order to replace a tile.
Any tips on how to do it? If not I might have to replace the whole renderer, that would be alot of work... I'm new to C++ and struggling to understand the unique pointers and all that stuff

**Comment by fallahn** [comment]
Sorry this isn't easily done without a bit of work. You'd probably need to keep your array of tile IDs around during run time, modify those, then resubmit them to build a new vertex array (if this happens infrequently then there should be very little impact on performance). If you have only a few tiles which change it might be OK to just draw a new sprite over the top of the tile layer. If you do decide to make your own renderer, I'd suggest starting at the basics. There's a tile map example on the sfml site [here](https://www.sfml-dev.org/tutorials/2.5/graphics-vertex-array.php#example-tile-map) which you can use to get started. The main difference is that instead of a fixed array of tile IDs you use the tile IDs loaded from the tmx file. Once you get that working with a single tile set you can start to build on it, adding support for more textures, while including the option to update tiles. No smart pointers needed! :) Don't forget you can always hop on the sfml irc or discord server if you want some advice, there's usually someone helpful around to give you a hand

**Comment by Luke004** [comment]
It really depends on the playstyle of the player lol. If he decides to burn down the whole forest it would be like 500 tiles of 40.000.
Will it affect performance a lot when I'll just create a new sprite over it, as you mentioned? That seems to be the most efficient solution for me right now

**Comment by fallahn** [comment]
The problem with sprites is that you have a `draw()` call for each one, which is one of the mosts expensive parts of rendering. A few sprites is OK, probably a few hundred is OK, but you'll eventually start to notice a slow down in performance. What you could do, now that I think about it, is have your own vertex array to draw tiles over the top. Each time a new damage tile is created, add it to the vertex array. This way you only need to draw one extra vertex array on top of the map, which contains all the damage tiles.

Viewport culling (ie only drawing what's in view) is also a good idea. It gets a bit trickier when using vertex arrays, but they can be broken into smaller parts - which is the idea behind the `Chunk` class in the example. I'd say try a vertex array first. If it gets too big or there's noticible performance problems, then look at splitting it into chunks.

**Comment by ldornbusch** [comment]
@fallahn: I am also trying to implement a setTile(..) function.. for the SFMLExample. I am just wondering about the ChunkArray vector inside the chunk: AFAIK is a chunk a part of a layer and a single Tileset (to avoid texture switching during painting the tiles). the ChunkArray is the vertexbuffer and the texture. If this is correct, I net only 1 ChunkArray for each chunk, but we declared a vector:
`std::vector<ChunkArray::Ptr> m_chunkArrays;`
What did I miss?
