### ISSUE TITLE
Proposel: tmx::TileSet::hasTile(id) & tmx::TileSet::getTile(id) & 

### ISSUE THREAD

**Issue by simonrenger** [fallahn/tmxlite#40]
Good day,

what is your opinion on those functions? I was in need in my project for them so I implemented them quick and dirty in this way:
`tmx::TileSet::hasTile`
```cpp
        bool hasTile(uint32_t a_id) const { return a_id >= m_firstGID && a_id <= getLastGID(); };
```
`tmx::TileSet::getTile(id)`
This could be optimized with C++17 and `std::find`. The reason why I return a pointer is because of `nullptr` and the ownership would be still clear at the `tmx::TileSet` class.
```cpp
        const Tile* getTile(uint32_t a_id) const {
            a_id = (getLastGID() - m_firstGID) - (getLastGID() - a_id);
            for (const auto& tile : m_tiles)
                if (tile.ID == a_id)
                    return &tile;
            return nullptr;
        }
```
If this approach is not modern enough you could return a `std::shared_ptr` the problem here would be that you have a small overhead.
```cpp
        const Tile* getTile(uint32_t a_id) const {
            a_id = (getLastGID() - m_firstGID) - (getLastGID() - a_id);
            for (const auto& tile : m_tiles)
                if (tile.ID == a_id)
                    return &tile;
            return nullptr;
        }
```

**Comment by fallahn** [comment]
Hi. This seems completely reasonable. As far as I know `std::find` is available pre-c++17 so using that would be preferable. I agree with returning a pointer to the tile and tileset ownership. Returning a nullptr also makes it clear that a tile does not exist. I'd also suggest using `std::uint32_t` rather than `unint32_t` as that implies the use of `<cstdint>` over `stdint.h`. Thanks!

**Comment by simonrenger** [comment]
I will add it to my fork and create a pull request. I will do quick research in terms of pre-c++17.
