### ISSUE TITLE
Issues with VS2019 [Win Toolkit 10.0/platform toolset v142]

### ISSUE THREAD

**Issue by Himan2104** [fallahn/tmxlite#71]
The library builds fine with Cmake and VS2019 however when trying one of the SFML examples to test run, I end up with :
```
1>D:\Libraries\TMXLite\include\tmxlite\detail\Log.hpp(131,1): error C2664: 'void OutputDebugStringW(LPCWSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCWSTR'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>D:\Libraries\TMXLite\include\tmxlite\detail\Log.hpp(131,50): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\debugapi.h(62,1): message : see declaration of 'OutputDebugStringW'
```

**Comment by fallahn** [comment]
Hi,
This is due to the `OutputDebugString` macro (here https://github.com/fallahn/tmxlite/blob/master/tmxlite/include/tmxlite/detail/Log.hpp#L131) resolving to `OutputDebugStringW` on some installations. The easiest work-around for this is to just comment it out if you don't mind log messages not being printed in visual studio's console (they're still printed to the main console window). Otherwise you can manually replace it with `OutputDebugStringA` which expects a `char*` rather than the `LPCWSTR` the wide char version expects. This page explains more about why this is https://docs.microsoft.com/en-us/windows/win32/intl/conventions-for-function-prototypes

**Comment by Himan2104** [comment]
Okay. I understand. Thanks for the help and the amazing library :)
