### ISSUE TITLE
pugixml is embedded

### ISSUE THREAD

**Issue by pedro-w** [fallahn/tmxlite#8]
I'd appreciate your thoughts on this - at the moment there's a copy of pugixml embedded in the tmxlite code. This makes it a little bit awkward if someone wants to use XML for some other part of the app. They'd have to include the header from tmxlite/detail/ , which looks like it was put there to make it 'private' (i.e. an implementation detail), or maybe have their own copy of the header (but not the source) and let the linker sort it out.

I was wondering if it would be possible to add an option to the CMakefile to allow an external copy of pugixml to be used? In that way tmxlite and pugixml would both be dependencies of the main app. I'm not very good on CMake.

**Comment by fallahn** [comment]
Yup I totally understand this. My original thinking was, however, to embed pugi (and miniz) in the project so that users didn't have to worry about linking any other dependencies, as that seemed to be one of the problems people were having with my previous tmx parser. I guess one possibility would be to export the pugi interface when building the shared libraries so that including the headers in your project will give you access to pugi functions. This should already be the case when statically linking. I'll give this some more thought.

**Comment by fallahn** [comment]
closed by #10
