### ISSUE TITLE
Support for object types

### ISSUE THREAD

**Issue by Eren121** [fallahn/tmxlite#90]
Does tmxlite supports object types rules ?

**Comment by Eren121** [comment]
And also tile property ?

**Comment by fallahn** [comment]
Not sure what you mean by type rules. An object will contain its type string as stored in the map file, available via `Object::getType()`. The map loader doesn't read the objecttypes.xml file as that's not part of the map, so you'll have to load that yourself.

The tile property of the object is available via `Object::getTileID()` and optionally `Object::getFlipFlags()`

**Comment by Eren121** [comment]
I mean that I think that many classes have properties: objects, tilesets, and individual tiles inside tileset.
Was I needed was individual tile properties. But it's ok, I found it under `Tileset::Tile::getProperties()`.

But objects have not tiles IDs, isn't it? So what is `Object::getTileID()`?

For object types, yes I mean the default properties, like a class default stored in `objecttypes.xml`.
Is it planned anytime soon by chance (or will a pull request be considered) ?

**Comment by fallahn** [comment]
From the [Tiled format document](https://doc.mapeditor.org/en/latest/reference/tmx-map-format/#object):

_id: Unique ID of the object. Each object that is placed on a map gets a unique id. Even if an object was deleted, no object gets the same ID. Can not be changed in Tiled. (since Tiled 0.11)_

This is the UID returned by `Object::getUID()`

_gid: A reference to a tile. (optional)_

This is the GID/global tile ID of the object returned by `Object::getTileID()`

Tile global tile IDs in Tiled start at 1. 0 represents an empty tile in the map. Each tileset starts at 0, and then the tile IDs in that tileset are added to `TileSet::getFirstGID()` to return the global ID of the tile in the map. I hope that makes sense. You can read more in the tileset documentation [here](https://doc.mapeditor.org/en/latest/reference/tmx-map-format/#tileset).

I haven't considered adding support for `objecttypes.xml` as I've always thought of it as more of an editor config, but I don't see why it couldn't be loaded if it is found in the same path as the current map. It should be trivial to use something like `std::unordered_map` to map the type strings to the loaded properties. Pull requests are always considered! 😉
