### ISSUE TITLE
New properties constructor + property map

### ISSUE THREAD

**Issue by Eren121** [fallahn/tmxlite#96]
Two more proposals related to properties ^^

1) In the `map.tmx`, properties are in a std::vector but a real use case is a `std::map<std::string, tmx::Property>` (access by name). Is it possible to de something like that ? Should eventually manage the duplicate, but that's the only edge case I see.

2) `Property` do not has a constructor from C++ type. For my personal use for example, I store a map for property with default values but I must use workaround with a `std::variant` because `Property` can only be constructed from xml, I just replicate `Property` but with modiable content. Is it possible to support construction from float, int, std::string, etc ?

Thanks!

**Comment by fallahn** [comment]
In the first case you are probably correct - it would make more sense to access properties by name, *however* this would break the API to change it. For now I would have to remain committed to `std::vector`. On a related note `std::unordered_map` would probably perform better for string keys 🙂 When loading your map you can of course copy the properties into your own map anyway - as this is what the map loader would be doing for you then there's going to be little to no noticeable difference in performance.

The second instance would, presumably, require a constructor which would look something like `explicit Property(std::int32_t value)` and `explicit Property(bool value)` so you can initialise a property object in a certain type? In this case you would need to overload the constructor for each type, which ought to be OK, as long as you don't get stung by implicit conversion (for instance between `float` and `int`). The thing with properties is that they're meant to be read-only, due to their ability to hold multiple types. Anyone who has ever written javascript will tell you the pain of having an object's underlying type mutated elsewhere in a program, leading to unexpected results 😉 Assertion helps with this of course, but I'd stop short of suggesting that we should add setters to the `Property` class.

**Comment by ldornbusch** [comment]
Again, just my two cents as a user of this library(feel free to ignore it :) ): 
I am using this small loop for retrieving the (Float)-Properties  be assured, on modern processors this should be not measurable for a single digit number of properties:
`        for (auto& p: tileObject->properties){
            if (propertyName==p.getName()){
                retVal = p.getFloatValue();
            }
        }
`
I made the experience that the data, if you really need it in a more flexible fashion, you should copy it to your own data structures. I see the tmxlite as a _reader_ of tmx files. It is not my object model to work on for my game. In this way I feel that the `std::vector` is the correct data-type: There is a list of properties in this tmx file(may be some people store their properties in a specific sequence and need support for this, maybe somewhen it is supported to use two properties with same name..).

**Comment by fallahn** [comment]
This is, indeed, the original intent of the library - a C++ representation of the data structures held in the xml file. It is another reason why the properties (and other classes) are all read-only. Of course, if a proposed feature makes sense and holds no unreasonable overhead, then I am also willing to consider it 😊

My current thinking is:

- extra constructors would be fine (as long as they don't run into implicit conversion problems)
- setters for `Property` values would be a bad idea
- changing the `vector` for (un)ordered_map is not going to happen for API reasons, as well as this design philosophy

**Comment by fallahn** [comment]
OK, that seems reasonable enough. Having indirect setters seems like a fair trade-off. If you want to prepare a PR which does what you need with the constructors, we can take it from there 😎
